### ISSUE TITLE
Accept 403 / other status code in detectDaemon()

### ISSUE THREAD

**Issue by ikreymer** [RangerMauve/auto-js-ipfs#13]
The check at: https://github.com/RangerMauve/auto-js-ipfs/blob/default/index.js#L581 now fails as kubo is returning 403 instead of 405 when using non-permissionned fetch here. One fix is to also check for 403, but perhaps it should just accept any status code, assuming connection went through, and fail only in the exception case?

**Comment by RangerMauve** [comment]
On it!

**Comment by RangerMauve** [comment]
I think for status code checks, we should avoid 404s and 0s (network failure) since that means it's unlikely to be a Kubo node.

**Comment by ikreymer** [comment]
agreed on 0 / network failure. i guess 404 could go either way - i suppose could be another service running on same port that's not kubo, so maybe that's safer, yea

**Comment by RangerMauve** [comment]
Out in 2.1.1
