### ISSUE TITLE
User-provided daemonURL should take precedence over known daemon types (and agregore).

### ISSUE THREAD

**Issue by ikreymer** [RangerMauve/auto-js-ipfs#14]
If a user specifies a custom `daemonURL` option, and that URL is a valid daemon URL, it should take precedence over the default known daemon types as well as Agregore.
However, in the current choose order: https://github.com/RangerMauve/auto-js-ipfs/blob/default/index.js#L41,
the default known daemon types are same priority and Agregore is higher.
Perhaps we need to add a USER_DAEMON_TYPE or something like that to ensure that it will always be ranked first, if successful.

**Comment by RangerMauve** [comment]
Cool so if I undserstand correctly priority should be like this:

- Agregore (if detected)
- User supplied daemon
- Found Kubo daemon
- Web3
- Estuary
- Readonly

**Comment by ikreymer** [comment]
yes, except user-supplied daemon should be above agregore, i think. eg, users should be able to use Agregore and provide an external daemon, too. So:
- User supplied daemon (if any)
- Agregore (if detected)
- Known kubo daemon (includes Brave daemon + default kubo port check) (if detected)
- ...

**Comment by RangerMauve** [comment]
Sounds good to me! :)

**Comment by RangerMauve** [comment]
Out in 2.2.0
