### ISSUE TITLE
Print log/warning instead of error for fallbacks?

### ISSUE THREAD

**Issue by ikreymer** [RangerMauve/auto-js-ipfs#6]
When checking for Agregore and local kubo node, auto-js-ipfs prints to `console.error`. This then appears as an error, but its an expected fallback, so may be confusing, perhaps it should just print log and/or have a verbose mode option?

https://github.com/RangerMauve/auto-js-ipfs/blob/default/index.js#L481
https://github.com/RangerMauve/auto-js-ipfs/blob/default/index.js#L498

**Comment by RangerMauve** [comment]
Switched to using console.warn and hiding the logs unless `debug = true`
